default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: root
  # adapter: mysql2
  # host: localhost
  # encoding: utf8 
  # pool: 5
  # username: root
  # password: root

development:
  <<: *default
  database: time_log_development
  
